<div id="firstTry">
	<div class="left">
		Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
		Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
		natoque penatibus et magnis dis parturient montes, nascetur
		ridiculus mus. Donec quam felis, ultricies nec, pellentesque
		eu, pretium quis, sem. Nulla consequat massa quis enim. Donec
		pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
	</div>
	<div class="middle">
		<img src="/img/testpix/tumblr.jpg" alt="" />
	</div>
	<div class="right">
		<img src="/img/testpix/annuit.coeptis.jpg" alt="" />
	</div>
</div>
<script type="text/javascript">
/* <[CDATA[ */
	jQuery(document).ready(function() {
		var max = $('#firstTry').children().maxHeight();
//		console.log(max);
	});
/* ]]> */
</script>