<div id="element">
    <div class="head">
		<ul id="tabs">
			<li class="active"><a href="javascript:;" class="is_tab" rel="/tabs/tab-one/" rev="<?php echo $this->uniqId; ?>">Tab 1</a></li>
			<li><a href="javascript:;" class="is_tab" rel="/tabs/tab-two/" rev="<?php echo $this->uniqId; ?>">Tab 2</a></li>
			<li class="last"><a href="javascript:;" class="is_tab" rel="/tabs/tab-three/" rev="<?php echo $this->uniqId; ?>">Tab 3</a></li>
		</ul>
    </div>
    <div id="<?php echo $this->uniqId; ?>" class="content">
    	Tab 1
    </div>
    <div class="foot"></div>
</div>