<ul id="navigation">
	<li><a href="/">Home</a></li>
	<li><a href="/minitest/">Minitests</a></li>
	<li><a href="/tabs/">Tabs</a></li>
	<li><a href="/layers/">Layers</a></li>
	<li><a href="/tinymce/">TinyMCE</a></li>
	<li><a href="/jquery-plugin/">jQuery PlugIns</a></li>
	<li><a href="/ajax-upload/">Ajax-Upload</a></li>
	<li><a href="/game-of-life/">Game of Life</a></li>
	<li><a href="/sierpinski/">Sierpinski-Fraktale</a></li>
</ul>
