<div id="gameOfLife">
	<canvas id="playground" class="playground is_playground" width="300" height="300"></canvas>
	<div class="control">
		<button class="is_nextGenBtn">Nächste Generation</button>
		Generation: <span class="is_generationCounter">0</span>
	</div>
</div>
<script type="text/javascript">
/* <![CDATA[ */
	$(document).ready(function() {
		GameOfLife.init();
	});
/* ]]> */
</script>